name: clippy
on:
  pull_request:
  push:
    branches:
      - main

jobs:
  clippy:
    name: Runs "cargo clippy" on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]

    steps:
      - uses: actions/checkout@v2

      - name: Setup Rust
        uses: dtolnay/rust-toolchain@stable

      - name: Setup Rust Cache
        uses: Swatinem/rust-cache@v2

      - name: cargo clippy
        run: cargo clippy -- -D warnings
