name: release

on:
  push:
    tags:
      - 'v*'

permissions:
  contents: write

jobs:
  publish-dry-run:
    name: "Runs cargo publish --dry-run"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Rust
        uses: dtolnay/rust-toolchain@stable

      - name: Setup Rust Cache
        uses: Swatinem/rust-cache@v2

      - name: publish crate
        run: cargo publish --dry-run

  publish-crate:
    name: Publish to crates.io
    needs: publish-dry-run
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Rust
        uses: dtolnay/rust-toolchain@stable

      - name: Setup Rust Cache
        uses: Swatinem/rust-cache@v2

      - name: Login to crates.io
        env:
          CRATES_IO_TOKEN: ${{ secrets.CRATES_IO_TOKEN }}
        run: cargo login ${CRATES_IO_TOKEN}

      - name: Publish Crate
        run: cargo publish

  create-release:
    name: Creates Release
    needs: publish-crate
    runs-on: ubuntu-latest
    steps:
      - name: Create Release
        id: create_release
        uses: actions/github-script@v7
        with:
          script: |
            await github.request(`POST /repos/${{ github.repository }}/releases`, {
              tag_name: "${{ github.ref }}",
              generate_release_notes: true
            });
